# Generated by Django 5.0.2 on 2024-11-27 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion_dos_api', '0003_alumnos_maestros'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materias',
            fields=[
                ('nrc', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('seccion', models.IntegerField(blank=True, null=True)),
                ('salon', models.CharField(blank=True, max_length=255, null=True)),
                ('programa_educativo', models.CharField(blank=True, max_length=255, null=True)),
                ('profesor_asignado', models.CharField(blank=True, max_length=255, null=True)),
                ('creditos', models.IntegerField(blank=True, null=True)),
                ('hora_inicio', models.IntegerField(blank=True, null=True)),
                ('minuto_inicio', models.IntegerField(blank=True, null=True)),
                ('hora_fin', models.IntegerField(blank=True, null=True)),
                ('minuto_fin', models.IntegerField(blank=True, null=True)),
                ('dias_json', models.TextField(blank=True, null=True)),
                ('creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('update', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
