# Generated by Django 5.0.2 on 2024-11-27 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion_dos_api', '0004_materias'),
    ]

    operations = [
        migrations.RenameField(
            model_name='materias',
            old_name='dias_json',
            new_name='dias',
        ),
    ]
