# Generated by Django 5.0.2 on 2024-12-02 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion_dos_api', '0005_rename_dias_json_materias_dias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materias',
            name='profesor_asignado',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='aplicacion_dos_api.maestros'),
        ),
    ]
